### ISSUE TITLE
Zadanie - problem z integracją Zipkina

### ISSUE THREAD

**Issue by mtsokol** [MaciejGawel/strangler#1]
Dzień dobry,

Piszę z pytaniem dotyczącym zadania laboratoryjnego - integracji Zipkina ze stworzonym systemem. 
Po ukończeniu `Strangle the Monolith` i odłączeniu `bookinfo/monolith` zadaniem jest zintegrowanie Zipkina do monitorowania systemu. 

Jako, że nie korzystałem wcześniej ze springa i zipkina próbowałem wykonać to poprzez przejście tutoriala integracji springa z zipkinem z Internetu:

- (w wersji jako aplikacja springa ze spring initializr)
https://www.baeldung.com/tracing-services-with-zipkin
https://medium.com/@Alibaba_Cloud/service-tracing-analysis-on-spring-cloud-applications-using-zipkin-b9457ad9227d
https://dzone.com/articles/spring-cloud-amp-spring-bootimplementing-zipkin-se
https://howtodoinjava.com/spring-cloud/spring-cloud-zipkin-sleuth-tutorial/

Brakuje w nich całej treści pliku pom.xml, i dodanie zgodnie z instrukcją samego `zipkin-server` do pom kończy się `java.lang.NoClassDefFoundError: org/springframework/boot/actuate/health/HealthStatusHttpMapper` w czasie budowania (również z rozwiązaniem z Internetu czyli dodanie `spring-boot-starter-actuator`).

Działający przykład z całym plikiem pom.xml był w https://dzone.com/articles/microservices-part-6-distributed-tracing-with-spri jednak tu dla wersji springa `1.5` w pom.xml nie ma polecenia: `mvn spring-boot:build-image -Dspring-boot.build-image.imageName=bookinfo/demo`:
```
[ERROR] Could not find goal 'build-image' in plugin org.springframework.boot:spring-boot-maven-plugin:1.5.10.RELEASE among available goals build-info, help, repackage, run, start, stop -> [Help 1]
```
A po podbiciu wersji do 2.3 ponownie jest `java.lang.NoClassDefFoundError: org/springframework/boot/actuate/health/HealthStatusHttpMapper`.

- (oraz jako gotowy kontener `openzipkin/zipkin`) który lokalnie działa, ale w systemie nie mam możliwości zarejestrowania jego do Eureki (tak jak jest to robione przez adnotacje w springu) by był widoczny dla innych usług

---

Czy można spytać o pomoc/wskazówkę do tego punktu?
Np. tutorial/instrukcję która będzie uruchomieniem zipkin server jako aplikacja spring boot z klientem Eureka dla wersji springa `2.3`?

Lub czy można z poziomu `docker-compose.yml` zarejestrować serwis w Eureka żeby skorzystać po prostu z obrazu `openzipkin/zipkin`?

**Comment by MaciejGawel** [comment]
Cześć, odpowiadając na pytania:

> tutorial/instrukcję która będzie uruchomieniem zipkin server jako aplikacja spring boot z klientem Eureka dla wersji springa 2.3?

Nie posiadam takiej instrukcji. Niestety, community nie najlepiej wspiera własny serwer Zipkina (https://github.com/openzipkin/zipkin/issues/2930#issuecomment-558682941) w najnowszej wersji. Możesz spróbować uruchomić serwer z następującymi zależnościami jednak trzeba rozwiązać kilka innych problemów:

```xml
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-zipkin</artifactId>
</dependency>
<dependency>
	<groupId>io.zipkin.java</groupId>
	<artifactId>zipkin-autoconfigure-ui</artifactId>
	<version>2.12.9</version>
</dependency>
<dependency>
	<groupId>io.zipkin.java</groupId>
	<artifactId>zipkin-server</artifactId>
	<version>2.12.9</version>
</dependency>
```

> dla wersji springa 1.5 w pom.xml nie ma polecenia: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=bookinfo/demo

Akceptowalnym rozwiązaniem jest stworzenie własnego Dockerfile bazującego na Java8 oraz dodającego jar.

> czy można z poziomu docker-compose.yml zarejestrować serwis w Eureka żeby skorzystać po prostu z obrazu openzipkin/zipkin?

Aby dodać Eureka Client wymagana jest modyfikacja głównej klasy. Więcej możesz o tym poczytać w tym issue: https://github.com/openzipkin/zipkin/issues/1870. Rozwiązaniem kompromisowym jest użycie obrazu Zipkin oraz mechanizmu Discovery dostępnego w Docker Compose.

**Comment by mtsokol** [comment]
@MaciejGawel Dzięki za pomoc!

Ostatecznie wariant z obrazem `openzipkin/zipkin` i bazowe discovery z docker-compose dało radę to zgrać.

Próbowałem jeszcze trafić w taką konfigurację pom.xml dla springa 2.3 żeby dało się zbudować obraz z serwerem zipkina i go uruchomić jednak na ten moment z dostępną dokumentacją i blogpostami (które są dla starszych wersji sprzed ~2 lat) bez większej wiedzy na ten temat nie udało się tego zrobić.
