### ISSUE TITLE
Zipkin - problemy

### ISSUE THREAD

**Issue by Zuroslaw** [MaciejGawel/strangler#3]
Dzień dobry,

Miałem spore problemy ze zintegrowaniem Zipkina w ćwiczeniu, a konkretnie z zarejestrowaniem go w Eureka (ostatecznie tego nie zrobiłem i wykorzystałem połączenie przez hostname w dockerze). Po fakcie zauważyłem, że nie tylko ja tak miałem, przeczytałem issue https://github.com/MaciejGawel/strangler/issues/1 i przechodziłem przez dokładnie te same problemy z próbą postawienia Zipkina na Spring Boocie (długo próbowałem i się poddałem, czytałem te same artykuły co autor). Próbowałem też workaroundów żeby zarejestrować Zipkina w Eurece bez Spring Boota, ale to też nie wyszło.

Tak jak wspominałem bardzo dużo czasu zajęła mi ta część pracy i w związku z tym chciałem zasugerować dodanie jakiejś informacji w konspekcie o tym, aby nie rejestrować Zipkina w Eurece, żeby zaoszczędzić czas innym.

**Comment by MaciejGawel** [comment]
Witam,

Rozszerzyłem opis zadania: https://github.com/MaciejGawel/strangler/commit/a43c77dc78ca1d0e85dfbe836696ed9508032a34
Zaktualizowana wersja jest dostępna pod adresem https://maciejgawel.github.io/strangler/assignment.html
